
# List all customers
GET http://0.0.0.0:3000/api/v1/customers 
content-type: application/json
x-auth-token: abc

###

# get a customer by ID
GET http://0.0.0.0:3000/api/v1/customers/1
content-type: application/json
x-auth-token: abc

###

# find a customer by name
GET http://0.0.0.0:3000/api/v1/customers?name=john
content-type: application/json
x-auth-token: abc

###

# list departments
GET http://0.0.0.0:3000/api/v1/departments 
content-type: application/json
x-auth-token: abc

###

# find department by ID
GET http://0.0.0.0:3000/api/v1/departments/60cdc9d4b21b0ded79e671e1
content-type: application/json
x-auth-token: abc
